version: "3"
services:
  redis:
    container_name: redis
    image: redis:7.0.5-alpine3.17
    ports:
      - 6379:6379
    volumes:
      - redis:/data # persistance
    networks:
      - webnet
    command: redis-server --requirepass ${REDIS_PASSWORD} --loglevel warning
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine3.17
    ports:
      - 5432:5432
    volumes:
      - postgres:/data # persistance
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - webnet
  api:
    container_name: api-dev
    build:
      context: . # Take dockerfile from root
      target: builder # Stop after builder
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # prevents to get overwritten from host computer as it's more specific
    ports:
      - 8080:8080 # left side needs to match with that what's in development.yml
    command: npm run start:dev # override npm run build from Dockerfile
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
volumes:
  redis:
    driver: local
  postgres:
    driver: local
networks:
  webnet:
